import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const reportPath = path.join(root, 'md/CODE_STATS.md');
const files = execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard', '-z'], {
  cwd: root,
  encoding: 'utf8',
})
  .split('\0')
  .filter(Boolean);
// Count source, tests, documentation and configuration; not generated dependency metadata.
const excluded = /(^|\/)(CODE_STATS\.md|pnpm-lock\.yaml|gradlew|gradlew\.bat|gradle-wrapper\.jar)$/;
const selected = [...new Set(files)]
  .filter((file) => !excluded.test(file) && existsSync(path.join(root, file)))
  .sort();
const temp = mkdtempSync(path.join(tmpdir(), 'our-place-cloc-'));
try {
  const list = path.join(temp, 'files.txt');
  writeFileSync(list, selected.join('\n') + '\n');
  const raw = execFileSync(
    'perl',
    [path.join(root, 'node_modules/cloc/lib/cloc'), '--json', '--quiet', `--list-file=${list}`],
    { cwd: root, encoding: 'utf8', maxBuffer: 8 * 1024 * 1024 },
  );
  const counts = JSON.parse(raw);
  const rows = Object.entries(counts)
    .filter(([name]) => name !== 'header' && name !== 'SUM')
    .sort(([a], [b]) => a.localeCompare(b, 'en'));
  rows.push(['Total', counts.SUM]);
  const report = [
    '# Code statistics',
    '',
    `Generated by cloc ${counts.header.cloc_version} using \`pnpm stats:cloc\` (requires Perl; Git for Windows includes it).`,
    '',
    'Counts the working source tree, including tests, documentation and configuration. Git-ignored files, dependency lockfiles, Gradle wrapper files and this report are excluded. Refresh before each commit and push.',
    '',
    '| Language | Files | Blank | Comment | Code |',
    '| --- | ---: | ---: | ---: | ---: |',
    ...rows.map(
      ([name, value]) => `| ${name} | ${value.nFiles} | ${value.blank} | ${value.comment} | ${value.code} |`,
    ),
    '',
  ].join('\n');
  if (!existsSync(reportPath) || readFileSync(reportPath, 'utf8') !== report)
    writeFileSync(reportPath, report);
  console.log(`md/CODE_STATS.md refreshed: ${counts.SUM.nFiles} files, ${counts.SUM.code} code lines.`);
} finally {
  rmSync(temp, { recursive: true, force: true });
}
